# Part 2b: Target Variable EDA

### Setup and basic info about dataset

In [32]:
import pandas as pd
import numpy as np
import matplotlib
from matplotlib import pylab as plt
from itertools import chain, combinations

In [2]:
features = pd.read_csv('../data/features_plus_descriptions.csv')
features.set_index('Feature Type and Number', inplace=True)

In [3]:
df_multilabel_strict = pd.read_csv('../data/multilabel_raw_data_strict.csv')
df_multilabel_tol = pd.read_csv('../data/multilabel_raw_data_tol.csv')
df_multiclass = pd.read_csv('../data/multiclass_target_raw_data.csv')
H_Best = ['H0_Best', 'H1_Best', 'H2_Best', 'H3_Best', 'H4_Best', 'H5_Best']

y_strict = df_multilabel_strict[H_Best]
y_tol = df_multilabel_tol[H_Best]
y_orig = df_multiclass[H_Best]

In [4]:
y_orig.head()

H0_Best  H1_Best  H2_Best  H3_Best  H4_Best  H5_Best
0        1        0        0        0        0        0
1        0        1        0        0        0        0
2        1        0        0        0        0        0
3        1        0        0        0        0        0
4        1        0        0        0        0        0

In [5]:
y_strict.head()

H0_Best  H1_Best  H2_Best  H3_Best  H4_Best  H5_Best
0        1        0        0        0        0        0
1        0        1        1        0        1        1
2        1        0        0        0        0        0
3        1        0        0        0        0        0
4        1        0        0        0        0        0

In [6]:
y_tol.head()

H0_Best  H1_Best  H2_Best  H3_Best  H4_Best  H5_Best
0        1        0        0        0        0        0
1        0        1        1        0        1        1
2        1        0        0        0        0        0
3        1        0        0        0        0        0
4        1        0        0        0        0        0

In [7]:
def show_patterns_tabulated(unique_rows, counts):
    """
    Function to display pattern groupings and return row counts.
    """
    pattern_counts = {}
    pattern_counter = 1
    pairs = [(1,2), (2,3), (3,4), (4,5), (1,3), (1,4), (1,5), (2,4), (2,5), (3,5)]
    triplets = [(1,2,3), (1,3,4), (2,3,4), (3,4,5), (1,2,4), (1,2,5), (1,3,5), (1,4,5), (2,4,5), (2,3,5)]
    quads = [(1,2,3,4), (1,2,3,5), (2,3,4,5), (1,2,4,5), (1,3,4,5)]
    for k in range(len(pairs)):
        i,j = pairs[k]
        sum_for_pair = 0
        vals_list = []
        print("pattern #" , pattern_counter)
        for a in range(len(unique_rows)):
            if unique_rows[a][i] == 1 and  unique_rows[a][j] == 1:
                print(unique_rows[a], counts[a])
                sum_for_pair += counts[a]
                vals_list.append(counts[a])
        print("sum for pair ({}, {}) = {} \n".format(i,j, sum_for_pair))
        pattern_counts[(i,j)] = vals_list
        pattern_counter +=1
    for k in range(len(triplets)):
        i,j,k = triplets[k]
        sum_for_triplet = 0
        vals_list = []
        print("pattern #" , pattern_counter)
        for a in range(len(unique_rows)):
            if unique_rows[a][i] == 1 and  unique_rows[a][j] == 1 and unique_rows[a][k] == 1:
                print(unique_rows[a], counts[a])
                sum_for_triplet += counts[a]
                vals_list.append(counts[a])
        print("sum for triplet({}, {}, {}) = {} \n".format(i,j,k, sum_for_triplet))
        pattern_counter +=1
        pattern_counts[(i,j,k)] = vals_list
    for k in range(len(quads)):
        i,j,k,m = quads[k]
        sum_for_quad = 0
        vals_list = []
        print("pattern #" , pattern_counter)
        for a in range(len(unique_rows)):
            case1 = (unique_rows[a][i] == 1 and  unique_rows[a][j] == 1)
            case2 = (unique_rows[a][k] == 1 and unique_rows[a][m] == 1)
            if case1 and case2:
                print(unique_rows[a], counts[a])
                sum_for_quad += counts[a]
                vals_list.append(counts[a])
        print("sum for quad ({}, {}, {}, {}) = {} \n".format(i,j,k,m, sum_for_quad))
        pattern_counts[(i,j,k,m)] = vals_list
        pattern_counter +=1
    print("pattern #" , pattern_counter)
    return pattern_counts

#### a. `y_original`: target based on Bridge et al. data

In [6]:
unique_rows_orig, counts_orig = np.unique(y_orig, axis=0,return_counts=True)
print(unique_rows_orig.shape)
for i in range(len(unique_rows_orig)):
    print(unique_rows_orig[i], counts_orig[i])

(6, 6)
[0 0 0 0 0 1] 624
[0 0 0 0 1 0] 617
[0 0 0 1 0 0] 748
[0 0 1 0 0 0] 486
[0 1 0 0 0 0] 1089
[1 0 0 0 0 0] 2554


#### b. `y_strict`: target using strict equality 

In [7]:
unique_rows_strict, counts_strict = np.unique(y_strict, axis=0,return_counts=True)
print(unique_rows_strict.shape)
for i in range(len(unique_rows_strict)):
    if np.sum(unique_rows_strict[i]) == 1:
        print(unique_rows_strict[i], counts_strict[i])

(32, 6)
[0 0 0 0 0 1] 624
[0 0 0 0 1 0] 476
[0 0 0 1 0 0] 620
[0 0 1 0 0 0] 347
[0 1 0 0 0 0] 594
[1 0 0 0 0 0] 2554


In [ ]:
#strict_pattern_counts = show_patterns_tabulated(unique_rows_strict, counts_strict)

In [ ]:
#for key in strict_pattern_counts.keys():
#    print(key, strict_pattern_counts[key])

In [ ]:
counts = []
for tup in stacks[0]:
    print(tup)
    counts.append(strict_pattern_counts[tup])
print(counts)

In [ ]:
positives = {i:0 for i in range(6)}
for a in range(len(counts_strict)):
    for s in range(len(unique_rows_strict[a])):
        if unique_rows_strict[a][s] == 1:
            positives[s] += counts_strict[a]
positives

#### c. `y_tol`: target using loose equality (`atol = 0.01`)

In [8]:
unique_rows_tol, counts_tol = np.unique(y_tol, axis=0,return_counts=True)
print(unique_rows_tol.shape) 
for i in range(len(unique_rows_tol)):
    if np.sum(unique_rows_tol[i]) == 1:
        print(unique_rows_tol[i], counts_tol[i])

(32, 6)
[0 0 0 0 0 1] 421
[0 0 0 0 1 0] 360
[0 0 0 1 0 0] 525
[0 0 1 0 0 0] 242
[0 1 0 0 0 0] 463
[1 0 0 0 0 0] 2554


In [ ]:
#tab_tol = show_patterns_tabulated(unique_rows_tol, counts_tol)


In [11]:
total_class_counts = {i:0 for i in range(6)}
for a in range(len(counts_tol)):
    for s in range(len(unique_rows_tol[a])):
        if unique_rows_tol[a][s] == 1:
            total_class_counts[s] += counts_tol[a]
print("total class counts:", total_class_counts)

total class counts: {0: 2554, 1: 1568, 2: 1041, 3: 1477, 4: 1547, 5: 1558}


In [11]:
def get_total_class_counts(unique_rows, counts):
    """
    Function to determine per class counts of appearances.
    """
    total_class_counts = {i:0 for i in range(6)}
    for a in range(len(counts)):
        for s in range(len(unique_rows[a])):
            if unique_rows[a][s] == 1:
                total_class_counts[s] += counts[a]
    print("total class counts:", total_class_counts)

In [33]:
def powerset(iterable):
    "powerset([1,2,3]) --> () (1,) (2,) (3,) (1,2) (1,3) (2,3) (1,2,3)"
    s = list(iterable)
    return chain.from_iterable(combinations(s, r) for r in range(len(s)+1))

In [50]:
def find_all_subpatterns(pattern):
    """
    Function to return subpatterns from a pattern.
    """
    argwhere1 = np.nonzero(pattern)
    print(argwhere1, type(argwhere1))
    sets = powerset(argwhere1)
    print([s for s in sets])
    subpatterns = []
    for s in sets:
        subp = np.ones(6)
        subp[s] = 0 
        subpatterns.append(subp)
    return subpatterns


In [51]:
find_all_subpatterns([1,0,1,0,1])

(array([0, 2, 4]),) <class 'tuple'>
[(), (array([0, 2, 4]),)]


[]

In [ ]:
def show_patterns_grouped_tabulated(unique_rows, counts,):
    pattern_counts = {}
    pattern_counter = 1

    for i in range(len(unique_rows)):
        # Get pattern
        pattern = unique_rows[i] 
        # Find where nonzero
        wherenonzero = np.transpose(np.nonzero(a))
        
        for j in range(len(pattern)):
            if pattern[j] == 1:
                
                

In [14]:
def show_patterns_tabulated_div_by_class_counts(unique_rows, counts, total_class_counts):
    """
    Function to display pattern groupings and return row counts.
    """
    
    counts_record = np.zeros_like(singlets)
    for k in range(len(singlets)):
        i = singlets[k]
        print("pattern #" , pattern_counter)
        for a in range(len(unique_rows)):
            if unique_rows[a][i] == 1:
                counts_record[i] = np.round(counts[a]/total_class_counts[i], decimals=3)
        pattern_counter += 1
    sorted_arg = np.argsort(counts_record)
    print(sorted_arg)
    print(unique_rows[sorted_arg], counts_record[sorted_arg])
        
    
    return pattern_counts

In [15]:
divclass = show_patterns_tabulated_div_by_class_counts(unique_rows_tol, counts_tol, total_class_counts)

pattern # 1
pattern # 2
pattern # 3
pattern # 4
pattern # 5
pattern # 6
[1 2 3 4 5 0]
[[0 0 0 0 1 0]
 [0 0 0 0 1 1]
 [0 0 0 1 0 0]
 [0 0 0 1 0 1]
 [0 0 0 1 1 0]
 [0 0 0 0 0 1]] [0 0 0 0 0 1]


In [ ]:
for k in range(len(pairs)):
        i,j = pairs[k]
        sum_for_pair = 0
        vals_list = []
        print("pattern #" , pattern_counter)
        for a in range(len(unique_rows)):
            if unique_rows[a][i] == 1 and  unique_rows[a][j] == 1:
                sum_for_pair += counts[a]
                vals_list.append(counts[a])
        for a in range(len(unique_rows)):
            if unique_rows[a][i] == 1 and  unique_rows[a][j] == 1:
             #   print(unique_rows[a], np.round(counts[a]/sum_for_pair, decimals=3))
                counts_record[1].append(np.round(counts[a]/sum_for_pair, decimals=3))
        print("sum for pair ({}, {}) = {} \n".format(i,j, sum_for_pair))
        pattern_counts[(i,j)] = vals_list
        pattern_counter +=1
       # sorted_arg = np.unravel_index(np.argsort(counts_record[1]), shape=counts_record[1].shape)
      #  sorted_arg = sorted(counts_record[1])
        sorted_arg = np.argsort(counts_record[1])
        print(unique_rows[sorted_arg], counts_record[sorted_arg])
    
    for k in range(len(triplets)):
        i,j,k = triplets[k]
        sum_for_triplet = 0
        vals_list = []
        print("pattern #" , pattern_counter)
        for a in range(len(unique_rows)):
            if unique_rows[a][i] == 1 and  unique_rows[a][j] == 1 and unique_rows[a][k] == 1:
                sum_for_triplet += counts[a]
                vals_list.append(counts[a])
        for a in range(len(unique_rows)):
            if unique_rows[a][i] == 1 and  unique_rows[a][j] == 1 and unique_rows[a][k] == 1:
              #  print(unique_rows[a], np.round(counts[a]/sum_for_triplet, decimals=3))
                counts_record[2].append( np.round(counts[a]/sum_for_triplet, decimals=3))
        print("sum for triplet({}, {}, {}) = {} \n".format(i,j,k, sum_for_triplet))
        pattern_counts[(i,j,k)] = vals_list
        pattern_counter +=1
        #sorted_arg = np.unravel_index(np.argsort(counts_record[2]), shape=counts_record[2].shape)
        sorted_arg = sorted(counts_record[2])
        print(unique_rows[sorted_arg], counts_record[sorted_arg])
    
    for k in range(len(quads)):
        i,j,k,m = quads[k]
        sum_for_quad = 0
        vals_list = []
        print("pattern #" , pattern_counter)
        for a in range(len(unique_rows)):
            case1 = (unique_rows[a][i] == 1 and  unique_rows[a][j] == 1)
            case2 = (unique_rows[a][k] == 1 and unique_rows[a][m] == 1)
            if case1 and case2:
                sum_for_quad += counts[a]
                vals_list.append(counts[a])
        for a in range(len(unique_rows)):
            case1 = (unique_rows[a][i] == 1 and  unique_rows[a][j] == 1)
            case2 = (unique_rows[a][k] == 1 and unique_rows[a][m] == 1)
            if case1 and case2:
                counts_record[3].append(np.round(counts[a]/sum_for_quad, decimals=3))
        print("sum for quad ({}, {}, {}, {}) = {} \n".format(i,j,k,m, sum_for_quad))
        pattern_counts[(i,j,k,m)] = vals_list
        pattern_counter +=1
        sorted_arg = sorted(counts_record[3])
        #sorted_arg = np.unravel_index(np.argsort(counts_record[3]), shape=counts_record[3].shape)
        print(unique_rows[sorted_arg], counts_record[sorted_arg])
    print("pattern #" , pattern_counter)

In [ ]:
for i in range(len(counts_tol)):
    print(unique_rows_tol[i], counts_tol[i])

In [ ]:
tol_pattern_counts = show_patterns_tabulated(unique_rows_tol, counts_tol)